import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import io.github.bonigarcia.wdm.WebDriverManager;
// javaScriptExecutor is a interface which have execute script method, Webdriver interface is diff , javaScriptExecutor not know about webdriver , so it can not hold instance of webdriver i.e. driver
// it can hold object of chromedriver : NO need of typecasting JavascriptExecutor js=driver; same for TakesScreenshot
public class javaScriptExecutorDemo {

	public static void main(String[] args) throws IOException, InterruptedException {
		// TODO Auto-generated method stub
		WebDriverManager.chromedriver().setup();
		ChromeOptions cp=new ChromeOptions();
		cp.addArguments("--remote-allow-origins=*");
		ChromeDriver driver=new ChromeDriver(cp);
		JavascriptExecutor js=driver;
		//syntax :  js.executeScript(Script,args)
		driver.get("https://demo.nopcommerce.com/login");
		driver.manage().window().maximize();
		
		
		//flash
		WebElement logoelement=	driver.findElement(By.xpath("//img[@alt='nopCommerce demo store']"));
		JavaScriptUtil.FlashByJS(logoelement, driver);
		
		//Drawing border of element & take screenshot
		/*
		WebElement logoelement=	driver.findElement(By.xpath("//img[@alt='nopCommerce demo store']"));
		JavaScriptUtil.drawBorder(logoelement, driver);
		   //suppose border k turant bad screenshot chahiye hme 
		TakesScreenshot ts=driver;
		File src=ts.getScreenshotAs(OutputType.FILE);
		File target=new File(".\\screenshots\\logo.png"); //     .\\ represent current file directory , hmne screenshots folder create kia hai usme logo.png ke name se save ho jayegi file
		FileUtils.copyFile(src, target);
		*/
		
		
		
		
		//Getting title of the page
		/*
		String title=JavaScriptUtil.getTitleByJS(driver);
		System.out.println(title);
		*/
		
		
		//to perform click action
		/*
		WebElement clickelement=driver.findElement(By.cssSelector(".ico-register"));
		JavaScriptUtil.clickElementByJS(clickelement, driver);
		*/
		
		//Generate/sent Alert
		
		//JavaScriptUtil.generateAlertByJS(driver, "This alert is generated by me");
		
		//Refreshing the page
		//JavaScriptUtil.refreshBrowserByJS(driver);
		
		//scroll page down 
		//JavaScriptUtil.ScrollDownPageUPByJS(driver);
		
		Thread.sleep(3000);
		
		//scroll up
		//JavaScriptUtil.scrollUPPageByJS(driver);
		
		//Zoom page
		//JavaScriptUtil.ZoomByJS(driver);
		
		
		
	}

}
